"""add seller to gem model

Revision ID: f47a0abc7f1d
Revises: bc95443719a6
Create Date: 2022-04-23 23:52:29.159924

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f47a0abc7f1d'
down_revision = 'bc95443719a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gem', sa.Column('seller_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gem', 'user', ['seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gem', type_='foreignkey')
    op.drop_column('gem', 'seller_id')
    # ### end Alembic commands ###
